version: 1
validation: sovereign
default_denom: ucavie
accounts: 
- name: alice
  coins:
  - 20000token
  - 200000000ucavie
- name: bob
  coins:
  - 10000token
  - 100000000ucavie
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
  - 5token
  - 100000ucavie
validators:
- name: alice
  bonded: 100000000ucavie
- name: validator1
  bonded: 200000000ucavie
- name: validator2
  bonded: 100000000ucavie